# Generated by Django 3.2.7 on 2021-09-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='avisos',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensajes',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='Productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nuevo',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=None),
        ),
    ]
